project:
  type: website
  output-dir: _site

website:
  title: "admiral"
  description: "Parent website for the admiral packages"
  site-url: /
  repo-url: https://github.com/pharmaverse
  google-analytics: "G-XXXXXX"
  open-graph: true
  favicon: favicon.png
  twitter-card:
    creator: "@roche"
    site: "@roche"
    card-style: "summary_large_image"
  search:
    location: navbar
    type: overlay
  navbar:
    background: dark
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: packages.qmd
      - href: functions.qmd
      - href: people.qmd
      - href: blog.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    toc-depth: 4
    toc-title: "Contents"
    html-math-method: katex
    include-in-header:
      - includes.html
    highlight-style: tango
